/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eriksandsten_utils_Win32Helper */

#ifndef _Included_org_eriksandsten_utils_Win32Helper
#define _Included_org_eriksandsten_utils_Win32Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eriksandsten_utils_Win32Helper
 * Method:    getWindowCaptionsByProcessId
 * Signature: (I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_eriksandsten_utils_Win32Helper_getWindowCaptionsByProcessId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_eriksandsten_utils_Win32Helper
 * Method:    getWindowCaptionsByWindowClassName
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_eriksandsten_utils_Win32Helper_getWindowCaptionsByWindowClassName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_eriksandsten_utils_Win32Helper
 * Method:    getWindowHandlesByWindowClassName
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_eriksandsten_utils_Win32Helper_getWindowHandlesByWindowClassName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_eriksandsten_utils_Win32Helper
 * Method:    getWindowHandleByProcessId
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_eriksandsten_utils_Win32Helper_getWindowHandleByProcessId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_eriksandsten_utils_Win32Helper
 * Method:    getWindowTitleByWindowHandle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eriksandsten_utils_Win32Helper_getWindowTitleByWindowHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_eriksandsten_utils_Win32Helper
 * Method:    getWindowHandleByWindowTitle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_eriksandsten_utils_Win32Helper_getWindowHandleByWindowTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_eriksandsten_utils_Win32Helper
 * Method:    setActiveWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_eriksandsten_utils_Win32Helper_setActiveWindow
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
